theme: jekyll-theme-minimal
title: Jiwoong Park
description: <p><b>Postdoctoral researcher </b><br><b>Department of ECE, Texas A&M University, USA</b> <br><b>jiwoong.park (at) tamu (dot) edu </b></p>
